name: deploy
on:
  push:
    branches:
      - main


jobs:
  deploy:
    if: ${{ github.repository_owner == 'cdloh' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run lint
      - name: Release
        run: npm run semantic-release
